export default {
    category: {
        categoriesFetched: "Categories have been fetched.",
        categoriesFetchError: "Categories could not be fetched.",
        categoryFetched: "Category has been fetched.",
        categoryFetchError: "Category could not be fetched.",
        categoryAdded: "Category has been added.",
        categoryAddError: "Category could not be added.",
        categoryEdited: "Category has been edited.",
        categoryEditError: "Category could not be edited.",
        categoryDeleted: "Category has been deleted.",
        categoryDeleteError: "Category could not be deleted.",
        validation: (field: string) => `${field} is required.`,
    },
    company: {
        companiesFetched: "Companies have been fetched.",
        companiesFetchError: "Companies could not be fetched.",
        companyFetched: "Company has been fetched.",
        companyFetchError: "Company could not be fetched.",
        companyAdded: "Company has been added.",
        companyAddError: "Company could not be added.",
        companyEdited: "Company has been edited.",
        companyEditError: "Company could not be edited.",
        companyDeleted: "Company has been deleted.",
        companyDeleteError: "Company could not be deleted.",
        companyNotFound:
            "Company that your trying to perform action on is not available.",
        validation: (field: string) => `${field} is required.`,
    },
};
